<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class bovinos extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $bovinos = [
            [
                'id_interno' => 107,
                'nombre' => null,
                'estatus_genetico' => 'Preñada',
                'fecha_nacimiento' => null,
                'fecha_destete' => null,
                'id_siniiga' => '2715170825',
                'id_registro' => null,
                'raza_id' => 13,
                'sexo_id' => 2,
                'upp_id' => 1,
                'propietario_id' => 4,
                'estatus_comercio_id' => 2,
                'madre_id_interno' => null,
                'padre_id_interno' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_interno' => 122,
                'nombre' => 'Rubi',
                'estatus_genetico' => 'Vacía',
                'fecha_nacimiento' => null,
                'fecha_destete' => null,
                'id_siniiga' => '2714762409',
                'id_registro' => null,
                'raza_id' => 11,  // Beefmaster
                'sexo_id' => 2,   // Hembra
                'upp_id' => 1,
                'propietario_id' => 4,
                'estatus_comercio_id' => 1,  // Puro
                'madre_id_interno' => null,
                'padre_id_interno' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_interno' => 100,                // Si id_interno es un entero, quítale las comillas
                'nombre' => null,
                'estatus_genetico' => 'Vacía',     // Asegúrate de que este valor esté en el ENUM de la base de datos
                'fecha_nacimiento' => null,        // Si la fecha no está disponible, usa null
                'fecha_destete' => null,           // Igual que la anterior
                'id_siniiga' => '2714306280',      // Asegúrate de que esto coincida con el tipo de dato en la base de datos
                'id_registro' => null,             // Usa null si no tienes valor para este campo
                'raza_id' => 11,
                'sexo_id' => 1,
                'upp_id' => 1,
                'propietario_id' => 4,
                'estatus_comercio_id' => 1,
                'madre_id_interno' => null,        // Si no tienes un valor, usa null
                'padre_id_interno' => null,        // Igual que la anterior
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_interno' => 101,                // Si id_interno es un entero, quítale las comillas
                'nombre' => 'Chikys',
                'estatus_genetico' => 'Vacía',     // Asegúrate de que este valor esté en el ENUM de la base de datos
                'fecha_nacimiento' => '2022-08-02',        // Si la fecha no está disponible, usa null
                'fecha_destete' => null,           // Igual que la anterior
                'id_siniiga' => '2717353216',      // Asegúrate de que esto coincida con el tipo de dato en la base de datos
                'id_registro' => null,             // Usa null si no tienes valor para este campo
                'raza_id' => 11,
                'sexo_id' => 2,
                'upp_id' => 1,
                'propietario_id' => 4,
                'estatus_comercio_id' => 1,
                'madre_id_interno' => 122,        // Si no tienes un valor, usa null (122)
                'padre_id_interno' => null,        // Igual que la anterior
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_interno' => 102,                // Si id_interno es un entero, quítale las comillas
                'nombre' => 'Dulce',
                'estatus_genetico' => 'Vacía',     // Asegúrate de que este valor esté en el ENUM de la base de datos
                'fecha_nacimiento' => '2023-01-27',        // Si la fecha no está disponible, usa null
                'fecha_destete' => null,           // Igual que la anterior
                'id_siniiga' => '2717353199',      // Asegúrate de que esto coincida con el tipo de dato en la base de datos
                'id_registro' => null,             // Usa null si no tienes valor para este campo
                'raza_id' => 13,
                'sexo_id' => 2,
                'upp_id' => 1,
                'propietario_id' => 4,
                'estatus_comercio_id' => 2,
                'madre_id_interno' => 107,        // Si no tienes un valor, usa null (107)
                'padre_id_interno' => null,        // Igual que la anterior
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_interno' => 104,                // Si id_interno es un entero, quítale las comillas
                'nombre' => null,
                'estatus_genetico' => 'Vacía',     // Asegúrate de que este valor esté en el ENUM de la base de datos
                'fecha_nacimiento' => null,        // Si la fecha no está disponible, usa null
                'fecha_destete' => null,           // Igual que la anterior
                'id_siniiga' => '2715218410',      // Asegúrate de que esto coincida con el tipo de dato en la base de datos
                'id_registro' => null,             // Usa null si no tienes valor para este campo
                'raza_id' => 13,
                'sexo_id' => 2,
                'upp_id' => 1,
                'propietario_id' => 4,
                'estatus_comercio_id' => 2,
                'madre_id_interno' => null,        // Si no tienes un valor, usa null
                'padre_id_interno' => null,        // Igual que la anterior
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_interno' => 105,                // Si id_interno es un entero, quítale las comillas
                'nombre' => 'Popis',
                'estatus_genetico' => 'Preñada',     // Asegúrate de que este valor esté en el ENUM de la base de datos
                'fecha_nacimiento' => null,        // Si la fecha no está disponible, usa null
                'fecha_destete' => null,           // Igual que la anterior
                'id_siniiga' => '2714948637',      // Asegúrate de que esto coincida con el tipo de dato en la base de datos
                'id_registro' => null,             // Usa null si no tienes valor para este campo
                'raza_id' => 13,
                'sexo_id' => 2,
                'upp_id' => 1,
                'propietario_id' => 4,
                'estatus_comercio_id' => 1,
                'madre_id_interno' => null,        // Si no tienes un valor, usa null
                'padre_id_interno' => null,        // Igual que la anterior
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_interno' => 106,
                'nombre' => null,
                'estatus_genetico' => 'Preñada',
                'fecha_nacimiento' => null,
                'fecha_destete' => null,
                'id_siniiga' => '2715218414',
                'id_registro' => null,
                'raza_id' => 13,
                'sexo_id' => 2,
                'upp_id' => 1,
                'propietario_id' => 4,
                'estatus_comercio_id' => 2,
                'madre_id_interno' => null,
                'padre_id_interno' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            // [
            //     'id_interno' => 107,
            //     'nombre' => null,
            //     'estatus_genetico' => 'Preñada',
            //     'fecha_nacimiento' => null,
            //     'fecha_destete' => null,
            //     'id_siniiga' => '2715170825',
            //     'id_registro' => null,
            //     'raza_id' => 13,
            //     'sexo_id' => 2,
            //     'upp_id' => 1,
            //     'propietario_id' => 4,
            //     'estatus_comercio_id' => 2,
            //     'madre_id_interno' => null,
            //     'padre_id_interno' => null,
            //     'created_at' => now(),
            //     'updated_at' => now()
            // ],
            [
                'id_interno' => 108,
                'nombre' => null,
                'estatus_genetico' => 'Preñada',
                'fecha_nacimiento' => null,
                'fecha_destete' => '2021-04-16',
                'id_siniiga' => '2716121864',
                'id_registro' => null,
                'raza_id' => 13,
                'sexo_id' => 2,
                'upp_id' => 1,
                'propietario_id' => 4,
                'estatus_comercio_id' => 2,
                'madre_id_interno' => null,
                'padre_id_interno' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_interno' => 109,
                'nombre' => null,
                'estatus_genetico' => 'Vacía',
                'fecha_nacimiento' => null,
                'fecha_destete' => null,
                'id_siniiga' => '2715218403',
                'id_registro' => null,
                'raza_id' => 13,
                'sexo_id' => 2,
                'upp_id' => 1,
                'propietario_id' => 4,
                'estatus_comercio_id' => 2,
                'madre_id_interno' => null,
                'padre_id_interno' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_interno' => 111,
                'nombre' => null,
                'estatus_genetico' => 'Preñada',
                'fecha_nacimiento' => null,
                'fecha_destete' => null,
                'id_siniiga' => '2715170822',
                'id_registro' => null,
                'raza_id' => 13,
                'sexo_id' => 2,
                'upp_id' => 1,
                'propietario_id' => 4,
                'estatus_comercio_id' => 2,
                'madre_id_interno' => null,
                'padre_id_interno' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_interno' => 114,
                'nombre' => null,
                'estatus_genetico' => 'Vacía',
                'fecha_nacimiento' => null,
                'fecha_destete' => null,
                'id_siniiga' => '2715170821',
                'id_registro' => null,
                'raza_id' => 13,
                'sexo_id' => 2,
                'upp_id' => 1,
                'propietario_id' => 4,
                'estatus_comercio_id' => 2,
                'madre_id_interno' => null,
                'padre_id_interno' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],

            [
                'id_interno' => 115,
                'nombre' => 'Galilea',
                'estatus_genetico' => 'Preñada',
                'fecha_nacimiento' => null,
                'fecha_destete' => null,
                'id_siniiga' => '2714941095',
                'id_registro' => null,
                'raza_id' => 11,  // Beefmaster
                'sexo_id' => 2,   // Hembra
                'upp_id' => 1,
                'propietario_id' => 4,
                'estatus_comercio_id' => 1,  // Puro
                'madre_id_interno' => null,
                'padre_id_interno' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_interno' => 116,
                'nombre' => null,
                'estatus_genetico' => 'Preñada',
                'fecha_nacimiento' => null,
                'fecha_destete' => null,
                'id_siniiga' => '2717353211',
                'id_registro' => null,
                'raza_id' => 13,  // Cruza
                'sexo_id' => 2,   // Hembra
                'upp_id' => 1,
                'propietario_id' => 4,
                'estatus_comercio_id' => 2,  // Comercial
                'madre_id_interno' => null,
                'padre_id_interno' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_interno' => 117,
                'nombre' => 'Gatita',
                'estatus_genetico' => 'Preñada',
                'fecha_nacimiento' => null,
                'fecha_destete' => null,
                'id_siniiga' => '2715512916',
                'id_registro' => null,
                'raza_id' => 11,  // Beefmaster
                'sexo_id' => 2,   // Hembra
                'upp_id' => 1,
                'propietario_id' => 4,
                'estatus_comercio_id' => 1,  // Puro
                'madre_id_interno' => null,
                'padre_id_interno' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            // [
            //     'id_interno' => 122,
            //     'nombre' => 'Rubi',
            //     'estatus_genetico' => 'Vacía',
            //     'fecha_nacimiento' => null,
            //     'fecha_destete' => null,
            //     'id_siniiga' => '2714762409',
            //     'id_registro' => null,
            //     'raza_id' => 11,  // Beefmaster
            //     'sexo_id' => 2,   // Hembra
            //     'upp_id' => 1,
            //     'propietario_id' => 4,
            //     'estatus_comercio_id' => 1,  // Puro
            //     'madre_id_interno' => null,
            //     'padre_id_interno' => null,
            //     'created_at' => now(),
            //     'updated_at' => now()
            // ],
            
            [
                'id_interno' => 128,
                'nombre' => null,
                'estatus_genetico' => 'Vacía',
                'fecha_nacimiento' => null,
                'fecha_destete' => null,
                'id_siniiga' => '2715907240',
                'id_registro' => null,
                'raza_id' => 13,  // Cruza
                'sexo_id' => 2,   // Hembra
                'upp_id' => 1,
                'propietario_id' => 4,
                'estatus_comercio_id' => 2,  // Comercial
                'madre_id_interno' => null,
                'padre_id_interno' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_interno' => 501,
                'nombre' => null,
                'estatus_genetico' => 'Preñada',
                'fecha_nacimiento' => null,
                'fecha_destete' => null,
                'id_siniiga' => '2715218398',
                'id_registro' => null,
                'raza_id' => 13,  // Ajustar según la raza correspondiente
                'sexo_id' => 2,
                'upp_id' => 2,
                'propietario_id' => 3,
                'estatus_comercio_id' => 2,
                'madre_id_interno' => null,
                'padre_id_interno' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_interno' => 502,
                'nombre' => null,
                'estatus_genetico' => 'Preñada',
                'fecha_nacimiento' => null,
                'fecha_destete' => null,
                'id_siniiga' => '2715218411',
                'id_registro' => null,
                'raza_id' => 13,  // Ajustar según la raza correspondiente
                'sexo_id' => 2,
                'upp_id' => 2,
                'propietario_id' => 3,
                'estatus_comercio_id' => 2,
                'madre_id_interno' => null,
                'padre_id_interno' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_interno' => 503,
                'nombre' => 'Atenea',
                'estatus_genetico' => 'Preñada',
                'fecha_nacimiento' => null,
                'fecha_destete' => null,
                'id_siniiga' => '2714941078',
                'id_registro' => '302875',
                'raza_id' => 11,
                'sexo_id' => 2,
                'upp_id' => 1,
                'propietario_id' => 4,
                'estatus_comercio_id' => 1,
                'madre_id_interno' => null,
                'padre_id_interno' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_interno' => 504,
                'nombre' => null,
                'estatus_genetico' => 'Vacía',
                'fecha_nacimiento' => null,
                'fecha_destete' => null,
                'id_siniiga' => '2715170827',
                'id_registro' => null,
                'raza_id' => 13,
                'sexo_id' => 2,
                'upp_id' => 2,
                'propietario_id' => 3,
                'estatus_comercio_id' => 2,
                'madre_id_interno' => null,
                'padre_id_interno' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_interno' => 505,
                'nombre' => null,
                'estatus_genetico' => 'Vacía',
                'fecha_nacimiento' => null,
                'fecha_destete' => null,
                'id_siniiga' => '2715170824',
                'id_registro' => null,
                'raza_id' => 13,
                'sexo_id' => 2,
                'upp_id' => 2,
                'propietario_id' => 3,
                'estatus_comercio_id' => 2,
                'madre_id_interno' => null,
                'padre_id_interno' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_interno' => 506,
                'nombre' => 'Sandy',
                'estatus_genetico' => 'Preñada',
                'fecha_nacimiento' => '2021-10-02',
                'fecha_destete' => null,
                'id_siniiga' => '2716121867',
                'id_registro' => null,
                'raza_id' => 13,
                'sexo_id' => 2,
                'upp_id' => 1,
                'propietario_id' => 3,
                'estatus_comercio_id' => 2,
                'madre_id_interno' => null,
                'padre_id_interno' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_interno' => 507,
                'nombre' => 'Afrodita',
                'estatus_genetico' => 'Preñada',
                'fecha_nacimiento' => null,
                'fecha_destete' => null,
                'id_siniiga' => '2714948602',
                'id_registro' => null,
                'raza_id' => 11,
                'sexo_id' => 2,
                'upp_id' => 1,
                'propietario_id' => 3,
                'estatus_comercio_id' => 1,
                'madre_id_interno' => null,
                'padre_id_interno' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_interno' => 508,
                'nombre' => 'Blackwidow',
                'estatus_genetico' => 'Preñada',
                'fecha_nacimiento' => '2022-01-30',
                'fecha_destete' => null,
                'id_siniiga' => '2716645995',
                'id_registro' => null,
                'raza_id' => 13,
                'sexo_id' => 2,
                'upp_id' => 1,
                'propietario_id' => 3,
                'estatus_comercio_id' => 2,
                'madre_id_interno' => 505,
                'padre_id_interno' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_interno' => 509,
                'nombre' => null,
                'estatus_genetico' => 'Preñada',
                'fecha_nacimiento' => null,
                'fecha_destete' => null,
                'id_siniiga' => '2713883045',
                'id_registro' => null,
                'raza_id' => 13,
                'sexo_id' => 2,
                'upp_id' => 1,
                'propietario_id' => 3,
                'estatus_comercio_id' => 2,
                'madre_id_interno' => null,
                'padre_id_interno' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_interno' => 510,
                'nombre' => 'Artemisa',
                'estatus_genetico' => 'Vacía',
                'fecha_nacimiento' => null,
                'fecha_destete' => null,
                'id_siniiga' => '2715512912',
                'id_registro' => '316346',
                'raza_id' => 11,
                'sexo_id' => 2,
                'upp_id' => 1,
                'propietario_id' => 3,
                'estatus_comercio_id' => 1,
                'madre_id_interno' => null,
                'padre_id_interno' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_interno' => 511,
                'nombre' => 'Estrella',
                'estatus_genetico' => 'Preñada',
                'fecha_nacimiento' => null,
                'fecha_destete' => null,
                'id_siniiga' => '2714948641',
                'id_registro' => '302611',
                'raza_id' => 11,
                'sexo_id' => 2,
                'upp_id' => 1,
                'propietario_id' => 3,
                'estatus_comercio_id' => 1,
                'madre_id_interno' => null,
                'padre_id_interno' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_interno' => 512,
                'nombre' => null,
                'estatus_genetico' => 'Preñada',
                'fecha_nacimiento' => null,
                'fecha_destete' => null,
                'id_siniiga' => '2715907238',
                'id_registro' => null,
                'raza_id' => 13,
                'sexo_id' => 2,
                'upp_id' => 2,
                'propietario_id' => 3,
                'estatus_comercio_id' => 2,
                'madre_id_interno' => null,
                'padre_id_interno' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_interno' => 513,
                'nombre' => 'Mantis',
                'estatus_genetico' => 'Vacía',
                'fecha_nacimiento' => '2022-06-06',
                'fecha_destete' => null,
                'id_siniiga' => '2716646004',
                'id_registro' => null,
                'raza_id' => 13,
                'sexo_id' => 2,
                'upp_id' => 1,
                'propietario_id' => 3,
                'estatus_comercio_id' => 2,
                'madre_id_interno' => 504,
                'padre_id_interno' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_interno' => 515,
                'nombre' => 'Flor',
                'estatus_genetico' => 'Receptora',
                'fecha_nacimiento' => '2023-01-17',
                'fecha_destete' => null,
                'id_siniiga' => '2717353215',
                'id_registro' => null,
                'raza_id' => 13,
                'sexo_id' => 2,
                'upp_id' => 1,
                'propietario_id' => 3,
                'estatus_comercio_id' => 2,
                'madre_id_interno' => 509,
                'padre_id_interno' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_interno' => 517,
                'nombre' => 'Leya',
                'estatus_genetico' => 'Vacía',
                'fecha_nacimiento' => null,
                'fecha_destete' => null,
                'id_siniiga' => '2715512690',
                'id_registro' => null,
                'raza_id' => 11,
                'sexo_id' => 2,
                'upp_id' => 1,
                'propietario_id' => 3,
                'estatus_comercio_id' => 1,
                'madre_id_interno' => null,
                'padre_id_interno' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_interno' => 518,
                'nombre' => 'Aisha',
                'estatus_genetico' => 'Vacía',
                'fecha_nacimiento' => '2022-03-01',
                'fecha_destete' => null,
                'id_siniiga' => '2716646000',
                'id_registro' => null,
                'raza_id' => 13,
                'sexo_id' => 2,
                'upp_id' => 1,
                'propietario_id' => 3,
                'estatus_comercio_id' => 2,
                'madre_id_interno' => 502,
                'padre_id_interno' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_interno' => 615,
                'nombre' => 'Mulan',
                'estatus_genetico' => 'Preñada',
                'fecha_nacimiento' => null,
                'fecha_destete' => null,
                'id_siniiga' => '2714941043',
                'id_registro' => '302611',
                'raza_id' => 11,
                'sexo_id' => 2,
                'upp_id' => 1,
                'propietario_id' => 2,
                'estatus_comercio_id' => 1,
                'madre_id_interno' => null,
                'padre_id_interno' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_interno' => 600,
                'nombre' => null,
                'estatus_genetico' => 'Preñada',
                'fecha_nacimiento' => null,
                'fecha_destete' => null,
                'id_siniiga' => '2717353212',
                'id_registro' => null,
                'raza_id' => 13,
                'sexo_id' => 2,
                'upp_id' => 1,
                'propietario_id' => 2,
                'estatus_comercio_id' => 1,
                'madre_id_interno' => null,
                'padre_id_interno' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_interno' => 601,
                'nombre' => null,
                'estatus_genetico' => 'Preñada',
                'fecha_nacimiento' => null,
                'fecha_destete' => null,
                'id_siniiga' => '2715218417',
                'id_registro' => null,
                'raza_id' => 13,
                'sexo_id' => 2,
                'upp_id' => 2,
                'propietario_id' => 2,
                'estatus_comercio_id' => 1,
                'madre_id_interno' => null,
                'padre_id_interno' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_interno' => 602,
                'nombre' => null,
                'estatus_genetico' => 'Vacía',
                'fecha_nacimiento' => null,
                'fecha_destete' => null,
                'id_siniiga' => '2716646005',
                'id_registro' => null,
                'raza_id' => 13,
                'sexo_id' => 2,
                'upp_id' => 1,
                'propietario_id' => 2,
                'estatus_comercio_id' => 1,
                'madre_id_interno' => null,
                'padre_id_interno' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_interno' => 603,
                'nombre' => null,
                'estatus_genetico' => 'Vacía',
                'fecha_nacimiento' => null,
                'fecha_destete' => null,
                'id_siniiga' => '2714603705',
                'id_registro' => null,
                'raza_id' => 13,
                'sexo_id' => 2,
                'upp_id' => 2,
                'propietario_id' => 2,
                'estatus_comercio_id' => 1,
                'madre_id_interno' => null,
                'padre_id_interno' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_interno' => 604,
                'nombre' => 'Koketa',
                'estatus_genetico' => 'Preñada',
                'fecha_nacimiento' => '2021-07-02',
                'fecha_destete' => null,
                'id_siniiga' => '2716121863',
                'id_registro' => null,
                'raza_id' => 13,
                'sexo_id' => 2,
                'upp_id' => 1,
                'propietario_id' => 2,
                'estatus_comercio_id' => 1,
                'madre_id_interno' => null,
                'padre_id_interno' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_interno' => 605,
                'nombre' => 'Aurora',
                'estatus_genetico' => 'Preñada',
                'fecha_nacimiento' => null,
                'fecha_destete' => null,
                'id_siniiga' => '2715512935',
                'id_registro' => '316350',
                'raza_id' => 11,
                'sexo_id' => 2,
                'upp_id' => 1,
                'propietario_id' => 2,
                'estatus_comercio_id' => 1,
                'madre_id_interno' => null,
                'padre_id_interno' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_interno' => 606,
                'nombre' => null,
                'estatus_genetico' => 'Preñada',
                'fecha_nacimiento' => null,
                'fecha_destete' => null,
                'id_siniiga' => '2715907234',
                'id_registro' => null,
                'raza_id' => 13,
                'sexo_id' => 2,
                'upp_id' => 2,
                'propietario_id' => 2,
                'estatus_comercio_id' => 1,
                'madre_id_interno' => null,
                'padre_id_interno' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_interno' => 607,
                'nombre' => 'Wanda',
                'estatus_genetico' => 'Vacía',
                'fecha_nacimiento' => '2022-04-09',
                'fecha_destete' => null,
                'id_siniiga' => '2716646001',
                'id_registro' => null,
                'raza_id' => 11,
                'sexo_id' => 2,
                'upp_id' => 1,
                'propietario_id' => 2,
                'estatus_comercio_id' => 1,
                'madre_id_interno' => 615,
                'padre_id_interno' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_interno' => 608,
                'nombre' => null,
                'estatus_genetico' => 'Preñada',
                'fecha_nacimiento' => null,
                'fecha_destete' => null,
                'id_siniiga' => '2715218402',
                'id_registro' => null,
                'raza_id' => 13,
                'sexo_id' => 2,
                'upp_id' => 2,
                'propietario_id' => 2,
                'estatus_comercio_id' => 1,
                'madre_id_interno' => null,
                'padre_id_interno' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_interno' => 609,
                'nombre' => 'Sia',
                'estatus_genetico' => 'Vacía',
                'fecha_nacimiento' => '2022-10-31',
                'fecha_destete' => null,
                'id_siniiga' => '2717353218',
                'id_registro' => null,
                'raza_id' => 13,
                'sexo_id' => 2,
                'upp_id' => 1,
                'propietario_id' => 2,
                'estatus_comercio_id' => 1,
                'madre_id_interno' => 603,
                'padre_id_interno' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_interno' => 610,
                'nombre' => 'Pili',
                'estatus_genetico' => 'Vacía',
                'fecha_nacimiento' => '2022-11-08',
                'fecha_destete' => null,
                'id_siniiga' => '2717353221',
                'id_registro' => null,
                'raza_id' => 13,
                'sexo_id' => 2,
                'upp_id' => 1,
                'propietario_id' => 2,
                'estatus_comercio_id' => 1,
                'madre_id_interno' => 601,
                'padre_id_interno' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_interno' => 611,
                'nombre' => 'Carly',
                'estatus_genetico' => 'Vacía',
                'fecha_nacimiento' => '2023-01-20',
                'fecha_destete' => null,
                'id_siniiga' => '2717353207',
                'id_registro' => null,
                'raza_id' => 13,
                'sexo_id' => 2,
                'upp_id' => 1,
                'propietario_id' => 2,
                'estatus_comercio_id' => 1,
                'madre_id_interno' => 600,
                'padre_id_interno' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_interno' => 612,
                'nombre' => 'Nina',
                'estatus_genetico' => 'Preñada',
                'fecha_nacimiento' => null,
                'fecha_destete' => null,
                'id_siniiga' => '2715512669',
                'id_registro' => '316350',
                'raza_id' => 11,
                'sexo_id' => 2,
                'upp_id' => 1,
                'propietario_id' => 2,
                'estatus_comercio_id' => 1,
                'madre_id_interno' => null,
                'padre_id_interno' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_interno' => 613,
                'nombre' => 'Mila',
                'estatus_genetico' => 'Vacía',
                'fecha_nacimiento' => '2023-04-14',
                'fecha_destete' => null,
                'id_siniiga' => '2717353208',
                'id_registro' => null,
                'raza_id' => 13,
                'sexo_id' => 2,
                'upp_id' => 1,
                'propietario_id' => 2,
                'estatus_comercio_id' => 1,
                'madre_id_interno' => 606,
                'padre_id_interno' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_interno' => 701,
                'nombre' => null,
                'estatus_genetico' => 'Vacía',
                'fecha_nacimiento' => null,
                'fecha_destete' => null,
                'id_siniiga' => '2715218412',
                'id_registro' => null,
                'raza_id' => 13,
                'sexo_id' => 2,
                'upp_id' => 1,
                'propietario_id' => 1,
                'estatus_comercio_id' => 1,
                'madre_id_interno' => null,
                'padre_id_interno' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_interno' => 702,
                'nombre' => null,
                'estatus_genetico' => 'Vacía',
                'fecha_nacimiento' => null,
                'fecha_destete' => null,
                'id_siniiga' => '2715218409',
                'id_registro' => null,
                'raza_id' => 13,
                'sexo_id' => 2,
                'upp_id' => 1,
                'propietario_id' => 1,
                'estatus_comercio_id' => 1,
                'madre_id_interno' => null,
                'padre_id_interno' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_interno' => 703,
                'nombre' => null,
                'estatus_genetico' => 'Preñada',
                'fecha_nacimiento' => null,
                'fecha_destete' => null,
                'id_siniiga' => '2715170828',
                'id_registro' => null,
                'raza_id' => 13,
                'sexo_id' => 2,
                'upp_id' => 1,
                'propietario_id' => 1,
                'estatus_comercio_id' => 1,
                'madre_id_interno' => null,
                'padre_id_interno' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_interno' => 704,
                'nombre' => null,
                'estatus_genetico' => 'Preñada',
                'fecha_nacimiento' => null,
                'fecha_destete' => null,
                'id_siniiga' => '2715907235',
                'id_registro' => null,
                'raza_id' => 13,
                'sexo_id' => 2,
                'upp_id' => 1,
                'propietario_id' => 1,
                'estatus_comercio_id' => 1,
                'madre_id_interno' => null,
                'padre_id_interno' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_interno' => 705,
                'nombre' => null,
                'estatus_genetico' => 'Preñada',
                'fecha_nacimiento' => null,
                'fecha_destete' => null,
                'id_siniiga' => '2715170819',
                'id_registro' => null,
                'raza_id' => 13,
                'sexo_id' => 2,
                'upp_id' => 1,
                'propietario_id' => 1,
                'estatus_comercio_id' => 1,
                'madre_id_interno' => null,
                'padre_id_interno' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_interno' => 706,
                'nombre' => null,
                'estatus_genetico' => 'Vacía',
                'fecha_nacimiento' => '2021-10-05',
                'fecha_destete' => null,
                'id_siniiga' => '2716121868',
                'id_registro' => null,
                'raza_id' => 13,
                'sexo_id' => 2,
                'upp_id' => 1,
                'propietario_id' => 1,
                'estatus_comercio_id' => 1,
                'madre_id_interno' => null,
                'padre_id_interno' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_interno' => 707,
                'nombre' => null,
                'estatus_genetico' => 'Vacía',
                'fecha_nacimiento' => null,
                'fecha_destete' => null,
                'id_siniiga' => '2715907241',
                'id_registro' => null,
                'raza_id' => 13,
                'sexo_id' => 2,
                'upp_id' => 1,
                'propietario_id' => 1,
                'estatus_comercio_id' => 1,
                'madre_id_interno' => null,
                'padre_id_interno' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_interno' => 708,
                'nombre' => null,
                'estatus_genetico' => 'Vacía',
                'fecha_nacimiento' => null,
                'fecha_destete' => null,
                'id_siniiga' => '2715907230',
                'id_registro' => null,
                'raza_id' => 13,
                'sexo_id' => 2,
                'upp_id' => 1,
                'propietario_id' => 1,
                'estatus_comercio_id' => 1,
                'madre_id_interno' => null,
                'padre_id_interno' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_interno' => 709,
                'nombre' => null,
                'estatus_genetico' => 'Vacía',
                'fecha_nacimiento' => null,
                'fecha_destete' => null,
                'id_siniiga' => '2715218405',
                'id_registro' => null,
                'raza_id' => 11,
                'sexo_id' => 2,
                'upp_id' => 1,
                'propietario_id' => 1,
                'estatus_comercio_id' => 1,
                'madre_id_interno' => null,
                'padre_id_interno' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_interno' => 710,
                'nombre' => 'Lassie',
                'estatus_genetico' => 'Vacía',
                'fecha_nacimiento' => '2022-11-19',
                'fecha_destete' => null,
                'id_siniiga' => '2717353217',
                'id_registro' => null,
                'raza_id' => 13,
                'sexo_id' => 2,
                'upp_id' => 1,
                'propietario_id' => 1,
                'estatus_comercio_id' => 1,
                'madre_id_interno' => null,
                'padre_id_interno' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_interno' => 711,
                'nombre' => 'Sasha',
                'estatus_genetico' => 'Vacía',
                'fecha_nacimiento' => null,
                'fecha_destete' => null,
                'id_siniiga' => '2715512601',
                'id_registro' => null,
                'raza_id' => 11,
                'sexo_id' => 2,
                'upp_id' => 1,
                'propietario_id' => 1,
                'estatus_comercio_id' => 1,
                'madre_id_interno' => null,
                'padre_id_interno' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_interno' => 713,
                'nombre' => 'Pelusa',
                'estatus_genetico' => 'Vacía',
                'fecha_nacimiento' => '2023-03-22',
                'fecha_destete' => null,
                'id_siniiga' => '2717353206',
                'id_registro' => null,
                'raza_id' => 13,
                'sexo_id' => 2,
                'upp_id' => 1,
                'propietario_id' => 1,
                'estatus_comercio_id' => 1,
                'madre_id_interno' => null,
                'padre_id_interno' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_interno' => 715,
                'nombre' => 'Shakira',
                'estatus_genetico' => 'Vacía',
                'fecha_nacimiento' => null,
                'fecha_destete' => null,
                'id_siniiga' => '2714948642',
                'id_registro' => '302609',
                'raza_id' => 11,
                'sexo_id' => 2,
                'upp_id' => 1,
                'propietario_id' => 1,
                'estatus_comercio_id' => 1,
                'madre_id_interno' => null,
                'padre_id_interno' => null,
                'created_at' => now(),
                'updated_at' => now()
            ]
            
        ];


        DB::table('ganado_bovinos')->insert($bovinos);
    }
}
